### ISSUE TITLE
Maturity / Production Readiness

### ISSUE THREAD

**Issue by markonian-117** [ZuInnoTe/spark-hadoopoffice-ds#1]
Hi Jörn,

I am really enthusiastic about your library and we want to use it ☺︎. I can also see that you update your library regularly and recently. 

May I ask your opinion about the production readiness or maturity of your library? Would you recommend using it in production?

Danke, Mark

**Comment by jornfranke** [comment]
Hi Mark,

I have unfortunately no feedback from someone using it in production at a large scale . That being said, it is mostly using the Apache POI library which is very mature (> 15 years) and used in many companies in a production environemnt.

Additionally, I developed for most of it unit test cases (automated) (see wiki you can see the reporting on number of tests as well as coverage in the static code analyzer).  Additionally, I tested it in small virtual clusters. Of course the library is open source and you can track down issues and ask me via github issues. At the moment, no known bug has been submitted. I would file the one received by email in Github or anyone can file it directly in Github. 

However, just a disclaimer that the library is not related to my work and thus it is based on best effort basis, but I am for sure willing to integrate your contributions. I am also interested in seeing which future features (see Github issues of HadoopOffice) are interesting for others.

I am also not aware of another library.

I hope it helps.

Best regards

**Comment by markonian-117** [comment]
Hi Martin,

Thanks for your straight answer ;)
I feel comfortable using it and reassuring that it is using Apache POI under the hood.

Best,
Mark

**Comment by jornfranke** [comment]
Thank you for the feedback. Let me know how it turns out.
btw. find more information about the underlying library HadoopOffice here: https://github.com/ZuInnoTe/hadoopoffice

**Comment by jornfranke** [comment]
as you can see there are continuously updates and quality enhancement. However, let me know if you think production readiness needs to be improved.
