### ISSUE TITLE
Date column parsing issue

### ISSUE THREAD

**Issue by jaypanchal** [ZuInnoTe/spark-hadoopoffice-ds#15]
When excel cell has cell value as a date for example 17-05-2018 19:10 it is converting that column into double type. So resultant value will be 17.0000 and spark consider it as a double datatype column

**Comment by jaypanchal** [comment]
The reason could be this 
ExcelConverterSimpleSpreadSheetCellDAO
`BigDecimal bd = (BigDecimal) this.decimalFormat.parse(currentCellValue, new ParsePosition(0));`
as this sentence will parse any string that starts with number / integer.

**Comment by jornfranke** [comment]
Hi,

No, it is not that. The converter takes as input a schema which can be autoinferred or you define it yourself. Can you please provide some source code? 

How did you define the schema? Is it autoinferred ? Then some valued might not be date. Or did you define it yourself?

What columns does the file contain?

Thank you.

**Comment by jornfranke** [comment]
It could be as well that you define the wrong date locale - this does not look like a US date.

**Comment by jaypanchal** [comment]
1. Yes, it is auto inferred. 
2. Particular date column (CreatedDate named column) has all the same date formatted value i.e. 15-02- 
    2018 13:15 (dd-MM-yyyy HH:mm) (Available in sample file)

3. And yeah, that is also true that, it is not US date, but, it in form of
```
dataFrameReader = dataFrameReader.load().sparkSession().read()
						.format("org.zuinnote.spark.office.excel")
						.option("read.spark.simpleMode","true")
						.option("read.spark.useHeader", "true")
						//.option("read.spark.useHeader.skipHeaderInEachSheet", "true")
						.option("read.locale.bcp47", "US")
						.option("read.lowfootprint", "true")
						.option("read.sheets", "");
				dataset = dataFrameReader.load(pathToFile);
```
Sample file [188.xlsx](https://github.com/ZuInnoTe/spark-hadoopoffice-ds/files/2068518/188.xlsx)

**Comment by jornfranke** [comment]
Well you define that it is US locale . Try the locale of the original file. Is it “DE”?
Check also read.spark.simpleMode.dateLocale

https://github.com/ZuInnoTe/spark-hadoopoffice-ds/blob/master/README.md

**Comment by jaypanchal** [comment]
Okay, let me give a try.
But, by this can we conclude, that any random date or timestamp (excluding available dateLocale) won't work ?

**Comment by jornfranke** [comment]
Not sure what you mean by random date, but the reasoning behind it was that Excel very often stores dates not as date but as string, eg for the case that it has not defined by the user as date in Excel (it happens very often). One could think about another option such as “use only Excel dates” , but this has the disadvantage that the string dates cannot be detected. 

Another alternative would be that you define in Spark a custom schema that is StringType for the date column and do any mapping to a custom date format. Probably this is preferred for “random” dates.

Another problem with random dates is that some date formats have conflicting information, eg one has first day and then month and then other first month and then day. This is very difficult to detect and handle automatically. Hence we can use the Power of Spark to do any custom processing on them.

**Comment by jornfranke** [comment]
I have not heard from you again, but feel free to check out also 1.2.0
