### ISSUE TITLE
Custom Schema Example

### ISSUE THREAD

**Issue by alaa-ismail** [ZuInnoTe/spark-hadoopoffice-ds#16]
Can you please provide an example on how to specify a custom schema when reading an Excel file? Thanks

**Comment by jornfranke** [comment]
Hi,

does the following work for you?

```
val sqlContext = sparkSession.sqlContext

val customSchema = StructType(Seq(
    StructField("FirstColumn", StringType, nullable = true),
    StructField("SecondColumn", IntegerType, nullable = true),
    StructField("ThirdColumn", DateType, nullable = true)))

val df = sqlContext.read
   .format("org.zuinnote.spark.office.excel")
   .option("read.locale.bcp47", "us").option("spark.read.simpleMode",true) 
 .option("read.spark.simpleMode.maxInferRows",1) 
.schema(customSchema)
.load('/path/to/file')
```

thank you.

best regards

**Comment by alaa-ismail** [comment]
Hi,
Thank you for the example. Unfortunately, I still can't get it to work with my file. I'm using python and Spark 2.2.1. 

This is the file I'm trying to read:
[Test.xlsx](https://github.com/ZuInnoTe/spark-hadoopoffice-ds/files/2538645/Test.xlsx)

Here is the code I'm using.
```
customSchema = StructType([
      StructField('num', StringType(), True),
      StructField('name', StringType(), True),
      StructField('id', StringType(), True),
      StructField('currentDate', DateType(), True),
      StructField('tag', StringType(), True),
      StructField('amount', DecimalType(20,2), True)
    ])

data = spark.read.format("org.zuinnote.spark.office.excel") \
                          .option("read.locale.bcp47", "us") \
                          .option("spark.read.simpleMode", "true") \
                          .option("read.spark.simpleMode.maxInferRows",1) \
                          .schema(customSchema) \
                          .load("/tmp/Test.xlsx")
print(data.take(1))
```
which returns this error:
```
java.lang.ClassCastException: org.apache.spark.sql.catalyst.util.GenericArrayData cannot be cast to org.apache.spark.unsafe.types.UTF8String
	at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow$class.getUTF8String(rows.scala:46)
	at org.apache.spark.sql.catalyst.expressions.GenericInternalRow.getUTF8String(rows.scala:194)
	at org.apache.spark.sql.catalyst.expressions.JoinedRow.getUTF8String(JoinedRow.scala:102)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1$$anonfun$apply$1.apply(FileFormat.scala:137)
	at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1$$anonfun$apply$1.apply(FileFormat.scala:136)
```

**Comment by jornfranke** [comment]
Thanks, do you have the full stacktrace? can you try it without custom schema to see if it can automatically infer it?

**Comment by jornfranke** [comment]
and for automatically inferring it you need to remove the option read.spark.simpleMode.maxInferRows

**Comment by jornfranke** [comment]
which version of the HadoopOffice library are you using?

**Comment by jornfranke** [comment]
Ah i think i know what happens. You have not simplemode activated: You must write          .option("read.spark.simpleMode", "true") 

I will fix this in the README.md

**Comment by alaa-ismail** [comment]
Thank you! It is working now. 
However, I'm having an issue reading the "tag" column in my excel file (which I uploaded earlier). Its value is a long number, but when reading it through spark it comes back as truncated in scientific notation (ie. 403577955365001 is read as 4.03578E+14). I tried different types in my custom schema (like DoubleType, LongType) but I still couldn't get it to read properly.
![image](https://user-images.githubusercontent.com/5109000/47957764-a5855c80-df92-11e8-91e9-471721ba65f4.png)

**Comment by jornfranke** [comment]
What was the outcome of DoubleType or LongType? 
It could be that  this is related to a default behavior in Spark/Pyspark,
Can you please also try DecimalType? (please set it as DecimalType with the correct precision and scale, just using DecimalType will default to 10,0 i think)

**Comment by alaa-ismail** [comment]
I tried the types below:
StringType - gives Row(tag=u'4.03578E+14')
DecimalType - gives Row(tag=Decimal('4.0357800000'))
DoubleType - gives Row(tag=4.03578)
FloatType - gives Row(tag=4.03577995300293)
LongType and IntegerType - throws an error
```
java.lang.ArithmeticException: Rounding necessary
	at java.math.BigDecimal.commonNeedIncrement(BigDecimal.java:4148)
	at java.math.BigDecimal.needIncrement(BigDecimal.java:4204)
	at java.math.BigDecimal.divideAndRound(BigDecimal.java:4112)
	at java.math.BigDecimal.setScale(BigDecimal.java:2452)
	at java.math.BigDecimal.longValueExact(BigDecimal.java:3090)
	at org.zuinnote.hadoop.office.format.common.converter.ExcelConverterSimpleSpreadSheetCellDAO.getDataAccordingToSchema(ExcelConverterSimpleSpreadSheetCellDAO.java:465)
	at org.zuinnote.spark.office.excel.DefaultSource$$anonfun$buildReader$3$$anonfun$apply$6.apply(DefaultSource.scala:353)
	at org.zuinnote.spark.office.excel.DefaultSource$$anonfun$buildReader$3$$anonfun$apply$6.apply(DefaultSource.scala:316)
```
It seems like spark is trying to cast '4.03578E+14' instead of the actual value in the spreadsheet, which leads to believe that the loss of precision is happening at an earlier stage.

I found this StackOverflow [question](https://stackoverflow.com/questions/46431561/apache-poi-dataformatter-returns-scientific-notation) with a similar issue in the Apache POI library.

**Comment by jornfranke** [comment]
Well by default it behaves like Excel, ie you see the numbers as you see them in Excel. 
One could think about an additional feature to ignore the representation in Excel and get the raw number (I would though not use the approach proposed in Stackoverflow, but a different one). E.g. one could have a option “hadoopoffice.read.simple.ignoreSpeadSheetNumberFormatting”
I don’t think it is a big change, but all packages have to be prepared including unit tests. I have to check when it could be ready.

As a quick fix you can fix the formatting in the Excel file.

**Comment by jornfranke** [comment]
In order to apply he quick fix by changing the format of those cells to Number and applying the appropriate numbering format (avoid scientific notation) or save the number as text (not recommended).
How was the Excel originally created? It is usually better to apply the concrete type in Excel (although the Excel type system is much more loose than the type system in a programing language).

**Comment by jornfranke** [comment]
please let me know if the quick fix worked for you.

The numbering format question is unfortunately more complex than expected in Excel (see also http://apache-poi.1045710.n5.nabble.com/Excel-Exponential-problem-td2310202.html). 
The problem is that Excel uses IEEE doubles to do calculation on numbers, but numbers may not fit exactly in an IEEE double but still be stored in a more precise format. 

The easiest way is indeed to set the correct numbering format in Excel itself. For the others, I would need to evaluate different possible cases and implement them (my original proposal may not work in all cases). One could be to interpret scientific format correctly in the HadoopOffice library, the other one to ignore number formats

I think if Excel applies the format Standard (ie no format specified) then it will use out of the box scientific notation. If you specify number then you will get the correct numbers.

**Comment by jornfranke** [comment]
+ i checked the Excel file, it contains it already in scientific notation.
The converter needs to detect scientific notation and adapt it

**Comment by jornfranke** [comment]
some further experiments with Excel:
It cannot represent the number: 123456789101112000001 (it is too large for Excel), ie you have to store it in text format in Excel and then HadoopOffice reads it correctly (as a number, it will discover that it is not really a next, but a number). For your case, you still have to fix the number formatting in Excel (to avoid scientific notation).

**Comment by jornfranke** [comment]
someone even wrote an article on wikipedia about this: https://en.wikipedia.org/wiki/Numeric_precision_in_Microsoft_Excel

I just released 1.2.1 that should at least interpret scientific notation correct. Nevertheless, it might be better to format them as Numbers in Excel or (if you do not use them in formulas) as text (allowing nearly any digit number in HadoopOffice, because HadoopOffice recognizes even text formats as numbers).

**Comment by jornfranke** [comment]
Did you have the chance to take a look at those considerations? thanks!

**Comment by alaa-ismail** [comment]
Thank you so much @jornfranke for adding these features so quickly. I tried the latest version and it is parsing the scientific notation correctly now. The emulateCSV option didn't work for me, but that's expected as if I use Excel to save my file as csv, it still keeps the scientific notation.

**Comment by jornfranke** [comment]
Great to hear, please let me know about other features / issues. We try to solve them as quickly as possible if it permits. The unstructuredness of Excel can be a problem from time to time :-)

**Comment by alaa-ismail** [comment]
Will do. Thank you again.
