### ISSUE TITLE
error on databricks

### ISSUE THREAD

**Issue by hiimhp** [ZuInnoTe/spark-hadoopoffice-ds#18]
I have the python code below on databricks and I am getting the rror "java.lang.NoSuchMethodError: org.apache.sql.execution.datasources.FileFormat.$init$(Lorg/apache/spark/sql/execution/datasources/FileFormat;)V

Please help

<code>from pyspark.sql import SQLContext sqlContext = SQLContext(sc)
df = sqlContext.read.format("org.zuinnote.spark.office.excel").options("read.locale.bcp47","us").load('/home/user/office/input')

**Comment by jornfranke** [comment]
Hi,

Which Spark and Scala version are you using? Could it be that you try with the Scala 2.11 version of the data source on Spark 2.4 with Scala 2.12?

Thank you 

best regards

**Comment by jornfranke** [comment]
Did this help you? Can we close the issue? Thanks
