### ISSUE TITLE
java.lang.NoSuchMethodError while using spark-hadoopoffice-ds_2.11 (v1.2.4)

### ISSUE THREAD

**Issue by mathewajik** [ZuInnoTe/spark-hadoopoffice-ds#19]
I am trying to use the spark-hadoopoffice-ds_2.11 (v1.2.4) library in one of my projects and I am stuck with the following error. 

```java
java.lang.NoSuchMethodError: org.apache.poi.xssf.usermodel.XSSFWorkbook.getProperties()Lorg/apache/poi/ooxml/POIXMLProperties;
        at org.zuinnote.hadoop.office.format.common.writer.msexcel.MSExcelWriter.prepareXSSFMetaData(MSExcelWriter.java:729)
        at org.zuinnote.hadoop.office.format.common.writer.msexcel.MSExcelWriter.prepareMetaData(MSExcelWriter.java:636)
        at org.zuinnote.hadoop.office.format.common.writer.msexcel.MSExcelWriter.close(MSExcelWriter.java:340)
        at org.zuinnote.hadoop.office.format.common.OfficeWriter.close(OfficeWriter.java:131)
        at org.zuinnote.hadoop.office.format.mapreduce.AbstractSpreadSheetDocumentRecordWriter.close(AbstractSpreadSheetDocumentRecordWriter.java:216)
        at org.zuinnote.spark.office.excel.ExcelOutputWriter.close(ExcelOutputWriter.scala:137)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$SingleDirectoryWriteTask.releaseResources(FileFormatWriter.scala:405)`
```
I got this error while running the following scala/spark code in cloudera hadoop cluster.

```scala
sparkSession.sql(sqlText)
        .repartition(1)
        .write
        .format("org.zuinnote.spark.office.excel")
        .option("read.locale.bcp47", "us")
        .option("write.spark.defaultsheetname", "Sheet1")
        .save(extractFile)
```
Here is how the dependencies look like in my maven pom file

```xml
<scala.version>2.11.8</scala.version>
 
<dependency>
 <groupId>com.github.zuinnote</groupId>
 <artifactId>spark-hadoopoffice-ds_2.11</artifactId>
 <version>1.2.4</version>
 <exclusions>
     <exclusion>
         <groupId>com.github.zuinnote</groupId>
         <artifactId>hadoopoffice-fileformat</artifactId>
     </exclusion>
     <exclusion>
         <groupId>org.apache.poi</groupId>
         <artifactId>poi</artifactId>
     </exclusion>
     <exclusion>
         <groupId>org.apache.poi</groupId>
         <artifactId>poi-ooxml</artifactId>
     </exclusion>
 </exclusions>
</dependency>
```
I have already tried going through the suggestions provided here - https://stackoverflow.com/questions/18231134/how-to-avoid-java-lang-nosuchmethoderror-org-apache-poi-util-ioutils-copyljava and made sure that there are no other versions of POI in use.

Unfortunately it did not resolve the error. Could you have a look at this issue and let me know if I am doing anything wrong?

Thanks in advance.

**Comment by jornfranke** [comment]
Thanks for notifying.

Why do you define exclusions of libraries in your Pom.xml? 

Have you tried to run one of the examples without modifications on your cluster? 


Eg the Scala examples? See how to guides:
https://github.com/ZuInnoTe/hadoopoffice/wiki

Try to build it with sbt

In maven you need to build a uber jar and shade commons-compress

**Comment by mathewajik** [comment]
About dependency exclusions - I was trying different things while investigating the error. And yes, some of the things I did, do not make sense.

I am trying to build the examples under "hadoopoffice/examples/scala-spark2-excel-out-ds". The sbt build has been running for the past 1 hour and appears to be stuck. This is the latest message from sbt:
`[warn] Merging 'META-INF\services\org.codehaus.stax2.validation.XMLValidationSchemaFactory.w3c' with strategy 'filterDistinctLines'`

I killed the build job and restarted it after cleaning up my .sbt and .ivy2 directories. Lets see how it goes.

**Comment by jornfranke** [comment]
They build on normally here , maybe you can provide the command that you are using, the full output and the sbt version ?

**Comment by mathewajik** [comment]
The SBT build for "hadoopoffice/examples/scala-spark2-excel-out-ds" failed in my windows laptop with the following error:

`[warn] Merging 'META-INF\services\org.codehaus.stax2.validation.XMLValidationSchemaFactory.w3c' with strategy 'filterDistinctLines'
[error] 131 errors were encountered during merge
[error] java.lang.RuntimeException: deduplicate: different file contents found in the following:
[error] C:\Users\<redacted>\.ivy2\cache\javax.servlet\javax.servlet-api\jars\javax.servlet-api-3.0.1.jar:javax/servlet/FilterConfig.class`

I ran the command `sbt clean +assembly` and used sbt version 1.2.8. The full output of sbt is available here - [sbt_build_error.txt](https://github.com/ZuInnoTe/spark-hadoopoffice-ds/files/2754056/sbt_build_error.txt)

**Comment by jornfranke** [comment]
Please clean up your local Maven cache and ivy cache.

It seems that you have a corrupt library there.

**Comment by jornfranke** [comment]
could this help you?

**Comment by jornfranke** [comment]
please open a new issue if the problem persists
