### ISSUE TITLE
"hadoopoffice.write.header.write" is only working for default sheet

### ISSUE THREAD

**Issue by dohongdayi** [ZuInnoTe/spark-hadoopoffice-ds#33]
https://github.com/ZuInnoTe/spark-hadoopoffice-ds/blob/19f86dd1273f43c347f135fd5b41b4e2fac48fe9/src/main/scala/org/zuinnote/spark/office/excel/ExcelOutputWriter.scala#L107-#L118

According to above code, when writing excel files, all sheets except default sheet won't have header.

**Comment by jornfranke** [comment]
that is correct and also the behaviour of the hadoopoffice library. However, it could be a useful enhancement that we can add in the next version. Could you also please share more about your use case?

**Comment by dohongdayi** [comment]
According to code, SpreadSheetCellDAO could work for different sheet, so ExcelOutputWriter could write excel file with multiple sheets, with which we can email with single attachment.

Or maybe "hadoopoffice.write.default.sheet.header.write" could be a better name through..

**Comment by jornfranke** [comment]
will be added soon as part of the nedt release. The option will be called hadoopoffice.write.header.writeheaderinallsheets
it will be by default false and can be set to true

**Comment by jornfranke** [comment]
ah wait sorry in know what you mean

**Comment by jornfranke** [comment]
that is in fact already supported: Just use the option "write.spark.defaultsheetname" : this sets the default sheetname to any sheetname you want

**Comment by dohongdayi** [comment]
Thanks, great work!
