### ISSUE TITLE
Skipped imported decimal values

### ISSUE THREAD

**Issue by danijelz** [ZuInnoTe/spark-hadoopoffice-ds#35]
When importing xlsx some decimal values are skipped. Superficially it looks like it depends on number of decimal places.

- Test values which cause first row to be ignored:
16884.924
1725.5523
- Test values which are imported correctly:
16884.9245
1725.5523
- Test values which are also imported correctly:
16884.924
1725.552

**Comment by jornfranke** [comment]
Hi, thank you for reporting this issue. Do you have an example file and source code so I can reproduce it? Spark-HadoopOffice has all of the [configuration options](https://github.com/ZuInnoTe/hadoopoffice/wiki/Hadoop-File-Format#configure) of the HadoopOffice library. For example, if you have the option "hadoopoffice.read.header.read" set to true then the first line is ignored.

**Comment by danijelz** [comment]
Hi @jornfranke, here is the data and code to reproduce the problem.

The  [Error.xlsx](https://github.com/ZuInnoTe/spark-hadoopoffice-ds/files/6341039/Error.xlsx) file is problematic one. By simply reading it and showing the content we can see that it doesn't import first row:

```
sparkSession.read().format("org.zuinnote.spark.office.excel").option("read.spark.simpleMode", true).load("Error.xlsx").show();
```
The result looks like this:
```
+-------------+
|       c0    |
+-------------+
|     null    |
|1725.5523    |
+-------------+
```

Insted, it should look like this:
```
+-------------+
|       c0    |
+-------------+
|16884.924    |
|1725.5523    |
+-------------+
```

By simly changing the value of first row to '16884.9245' as done in [NoError2.xlsx](https://github.com/ZuInnoTe/spark-hadoopoffice-ds/files/6341040/NoError2.xlsx), or value of second row to 1725.552 as done in [NoErrror1.xlsx](https://github.com/ZuInnoTe/spark-hadoopoffice-ds/files/6341042/NoErrror1.xlsx), the first row is imported correctly.

I also tried with header and it works the same. The only thing that helped was providing the custom schema which declared the row to be of 'DoubleType'.

**Comment by jornfranke** [comment]
thanks a lot. Now it is clear for me. I will try to reproduce it and fix it this week.

**Comment by jornfranke** [comment]
I can see an issue, but it is not the same as yours. The numbers are read correctly, but they are interpreted as integers. I can see also that your Excel internally stores them in String format.

**Comment by jornfranke** [comment]
Will need to spend a bit of more time.

**Comment by jornfranke** [comment]
Ok,  I found another bug, which I could fix. Now I can also reproduce your issue and look into it

**Comment by jornfranke** [comment]
thanks a lot for reporting this. I integrated a fix and test case and it should work in 1.5 which will be released the coming days.
Btw. I also discovered that since some Spark version (I do not know exactly which one) all HadoopOffice options that contained a capital letter were not recognized properly. For instance, if you activate low footprint mode it would have no effect in Spark (but all other Big Data platforms). Thanks for the detailed reporting and test cases, so that I could reproduce it.

**Comment by jornfranke** [comment]
should be fixed with the release 1.5.0 from yesterday, please check

**Comment by danijelz** [comment]
Sorry, can't do that until Monday since I'm on vacation. I will try to test it as soon as possible.

**Comment by jornfranke** [comment]
no worries take your time and thank you for reporting

**Comment by danijelz** [comment]
It works now. Thanks for quick response.
