### ISSUE TITLE
write.spark.useHeader is not working

### ISSUE THREAD

**Issue by rahul1991ghantasala** [ZuInnoTe/spark-hadoopoffice-ds#4]
I am trying to write a DF to excel sheet in spark 2.1.0 with the header row.

```
val sampleDF: DataFrame = spark.createDataFrame(Seq(
      (2, "abc"),
      (2, "def"),
      (4, "123")

    )).toDF("id", "text")

    sampleDF.repartition(1).write
      .format("org.zuinnote.spark.office.excel")
      .option("write.locale.bcp47", "de")
      .option("write.spark.useHeader","true")
      .mode(SaveMode.Overwrite)
      .save("/home/vghantasala/header.xlsx")
```

the above code does not insert the header row (a row with "id" and "text" cols) in the excel sheet. It just inserts the contents of the DF into the excel sheet
Am I missing something here ?

Thanks

**Comment by jornfranke** [comment]
The useHeader parameter is only in version 1.0.4 supported. This will be released end of July.

**Comment by jornfranke** [comment]
The parameter in version 1.0.4 is Boolean not String (see also integration tests):
> option("write.spark.useHeader",true)

**Comment by jornfranke** [comment]
i just saw that you use the locale DE (for Germany) - probably you took this from the examples, maybe EN would be more appropriate for you? Depending on the locale numbers are formatted differently...

**Comment by jornfranke** [comment]
added in version 1.0.4
